### ISSUE TITLE
Bardo failing in ClojureScript

### ISSUE THREAD

**Issue by acron0** [pleasetrythisathome/bardo#8]
Hi,

Receiving the following error when using bardo in ClojureScript:

```
clojure.lang.ExceptionInfo: Could not locate cljs/core/match__init.class or cljs/core/match.clj on classpath. at line 1 file:/home/acron/.m2/repository/bardo/bardo/0.1.2-SNAPSHOT/bardo-0.1.2-SNAPSHOT.jar!/bardo/interpolate.cljc {:file "file:/home/acron/.m2/repository/bardo/bardo/0.1.2-SNAPSHOT/bardo-0.1.2-SNAPSHOT.jar!/bardo/interpolate.cljc", :line 1, :column 1, :tag :cljs/analysis-error}
	at clojure.core$ex_info.invoke(core.clj:4593)
	at cljs.analyzer$error.invoke(analyzer.cljc:384)
	at cljs.analyzer$analyze_seq.invoke(analyzer.cljc:1898)
	...
```
Steps to reproduce:

  * `lein new figwheel bardo-test -- --om`
  * `cd bardo-test`
  * Add `[bardo "0.1.2-SNAPSHOT"]` to `:dependencies` in `project.clj`
  * `lein figwheel`
  * Navigate to `http://localhost:3449/` in browser (I was in Chrome 44)
  * In REPL type `(require '[bardo.interpolate :refer [interpolate]])`

**Comment by den1k** [comment]
@pleasetrythisathome do the deps in boot.clj need to be updated? I had only updated the profile.clj ones.

**Comment by den1k** [comment]
@acron0 @pleasetrythisathome I think using this in boot would fix it:
```
(set-env!
  :dependencies '[[leiningen-core "2.5.1"]])
(use 'leiningen.core.project)

(eval (read-string (slurp "project.clj")))

(set-env!
  :source-paths (set (:source-paths project))
  :resource-paths (set (:resource-paths project))
  :dependencies (vec (:dependencies project)))
```

**Comment by acron0** [comment]
I have never used boot for a project before, so bear with me...

**Comment by den1k** [comment]
@acron0 this is about `boot` being used to deploy it to clojars, where it defines the dependencies and the version.
For a local fix you can clone the repo, cd into it, run `lein install` and then in your project use `[bardo "0.1.0"]` (as specified in the lein profile.clj). This should work. However @pleasetrythisathome or I will fix this soon.

**Comment by acron0** [comment]
Ok, superb, thank you!

**Comment by pleasetrythisathome** [comment]
i just pushed a new snapshot. boot deps needed to be updated as @den1k said.

**Comment by pleasetrythisathome** [comment]
i also removed the bardo/project.clj to prevent future confusion.

**Comment by pleasetrythisathome** [comment]
that said, @acron0, you do not need to use boot to use bardo as a dependency, project built with boot are jars just like lein projects.

**Comment by acron0** [comment]
Sorry, it's still not working :( So, the `require` works without complaining...but any attempt to use the refer'd functions results in:

```
my-ns.core> (require '[bardo.interpolate :refer [interpolate]])
nil
my-ns.core> ((interpolate 0 10) 0.5)
ExceptionInfo #<ReferenceError: bardo is not defined>  clojure.core/ex-info (core.clj:4593)
```

**Comment by pleasetrythisathome** [comment]
that's strange. i'll look into it this afternoon. are you using
0.1.2-SNAPSHOT?

**Comment by acron0** [comment]
I am, yeah.

**Comment by acron0** [comment]
Should I create a new issue?

**Comment by acron0** [comment]
Never mind, PEBCAK.

**Comment by pleasetrythisathome** [comment]
Pushed a new snapshot version, updated boot to the new version that supports cljc. please make sure you're using clojure/clojurescript versions that support cljc (<= 1.7.0 version)
